// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_previews.sql

package db

import (
	"context"
)

const countLinkPreviews = `-- name: CountLinkPreviews :one
SELECT COUNT(*) FROM link_previews
`

func (q *Queries) CountLinkPreviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkPreviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllLinkPreviews = `-- name: DeleteAllLinkPreviews :exec
DELETE FROM link_previews
`

func (q *Queries) DeleteAllLinkPreviews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllLinkPreviews)
	return err
}

const deleteLinkPreview = `-- name: DeleteLinkPreview :exec
DELETE FROM link_previews
  WHERE url = $1
`

func (q *Queries) DeleteLinkPreview(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, deleteLinkPreview, url)
	return err
}

const getLinkPreview = `-- name: GetLinkPreview :one
SELECT _id, url, generated_at, last_accessed_at, access_count FROM link_previews
  WHERE url = $1
`

func (q *Queries) GetLinkPreview(ctx context.Context, url string) (LinkPreview, error) {
	row := q.db.QueryRow(ctx, getLinkPreview, url)
	var i LinkPreview
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.GeneratedAt,
		&i.LastAccessedAt,
		&i.AccessCount,
	)
	return i, err
}

const listLinkPreviews = `-- name: ListLinkPreviews :many
SELECT _id, url, generated_at, last_accessed_at, access_count FROM link_previews
  ORDER BY last_accessed_at DESC
`

func (q *Queries) ListLinkPreviews(ctx context.Context) ([]LinkPreview, error) {
	rows, err := q.db.Query(ctx, listLinkPreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkPreview
	for rows.Next() {
		var i LinkPreview
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.GeneratedAt,
			&i.LastAccessedAt,
			&i.AccessCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkPreviewsPaginated = `-- name: ListLinkPreviewsPaginated :many
SELECT _id, url, generated_at, last_accessed_at, access_count FROM link_previews
  ORDER BY last_accessed_at DESC
  LIMIT $1 OFFSET $2
`

type ListLinkPreviewsPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListLinkPreviewsPaginated(ctx context.Context, arg ListLinkPreviewsPaginatedParams) ([]LinkPreview, error) {
	rows, err := q.db.Query(ctx, listLinkPreviewsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkPreview
	for rows.Next() {
		var i LinkPreview
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.GeneratedAt,
			&i.LastAccessedAt,
			&i.AccessCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLinkPreviewAccessed = `-- name: RecordLinkPreviewAccessed :execrows
UPDATE link_previews
  SET last_accessed_at = NOW(),
    access_count = access_count + 1
  WHERE url = $1
`

func (q *Queries) RecordLinkPreviewAccessed(ctx context.Context, url string) (int64, error) {
	result, err := q.db.Exec(ctx, recordLinkPreviewAccessed, url)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordLinkPreviewCreated = `-- name: RecordLinkPreviewCreated :exec
INSERT INTO link_previews (url, generated_at, last_accessed_at, access_count)
  VALUES ($1, NOW(), NOW(), 1)
  ON CONFLICT(url)
  DO UPDATE SET
    generated_at = NOW(),
    last_accessed_at = NOW(),
    access_count = link_previews.access_count + 1
  RETURNING _id, url, generated_at, last_accessed_at, access_count
`

func (q *Queries) RecordLinkPreviewCreated(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, recordLinkPreviewCreated, url)
	return err
}
