// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Domain struct {
	ID                int64
	UpdatedAt         time.Time
	Domain            string
	IncludeSubdomains *bool
	Authorized        *bool
}

type Log struct {
	ID            int64
	LoggedAt      time.Time
	RequestMethod *string
	RequestPath   *string
	HttpStatus    *int32
	Url           *string
	Hostname      *string
	Message       *string
	Err           *string
}
