// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Log struct {
	ID            int64
	LoggedAt      pgtype.Timestamp
	RequestMethod *string
	RequestPath   *string
	HttpStatus    *int32
	Url           *string
	Hostname      *string
	Message       *string
	Err           *string
}
